// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpK2y9bO6QgyzXf6clNLsuIAP3AsIFkbA',
    appId: '1:89905596409:web:07948bfa238c08eaaf1f28',
    messagingSenderId: '89905596409',
    projectId: 'simplefirebaseapp-c7cce',
    authDomain: 'simplefirebaseapp-c7cce.firebaseapp.com',
    storageBucket: 'simplefirebaseapp-c7cce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzAUBdp11kfhd2fFInkH1o1l-4RdO7sWc',
    appId: '1:89905596409:android:2fb39cee9763cf78af1f28',
    messagingSenderId: '89905596409',
    projectId: 'simplefirebaseapp-c7cce',
    storageBucket: 'simplefirebaseapp-c7cce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8eevFbVenHTyN40WAsyV5pSXY4Hosrwc',
    appId: '1:89905596409:ios:a99df560f6a8ffa1af1f28',
    messagingSenderId: '89905596409',
    projectId: 'simplefirebaseapp-c7cce',
    storageBucket: 'simplefirebaseapp-c7cce.appspot.com',
    iosClientId: '89905596409-f3nrsfqim2q4t10l9ap0klme4i54josa.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8eevFbVenHTyN40WAsyV5pSXY4Hosrwc',
    appId: '1:89905596409:ios:153e9f57ee5af075af1f28',
    messagingSenderId: '89905596409',
    projectId: 'simplefirebaseapp-c7cce',
    storageBucket: 'simplefirebaseapp-c7cce.appspot.com',
    iosClientId: '89905596409-m1djlk463krkna9i1l409h70ffdstbje.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFirebaseApp.RunnerTests',
  );
}
